# Machine Learning Hounours Final Project
# Witwatersrand University
## Simbarashe Mhlanga (1325952)

## Project Name: Who to give the loan predicting loan default

# Import Libraries

In [36]:
import os
import pandas as pd
import numpy as np
from sklearn import preprocessing,metrics 
from IPython.core.display import HTML
pd.set_option("display.max_columns",75)
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn import linear_model,svm
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve

In [37]:
data_train = pd.read_csv('train_v2.csv')

In [38]:
data_train.head()

,id,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,f38,...,f743,f744,f745,f746,f747,f748,f749,f750,f751,f752,f753,f754,f755,f756,f757,f758,f759,f760,f761,f762,f763,f764,f765,f766,f767,f768,f769,f770,f771,f772,f773,f774,f775,f776,f777,f778,loss
0,1,126,10,0.686842,1100,3,13699,7201.0,4949.0,126.75,126.03,7,0.7607,0.7542,612922,0.7236,0.7236,0.5171,0.7236,0.8476,0.7876,1.097851e+09,89,66,998046.0,89.0,89.0,89.00,89.00,89.0,0.9271,0,0,0,5,0,0,...,-21.82,49.18,1.0435,-0.9066,1.5883,3.4154,2.8283,2.3451,0.030594,1.7418,1.5271,0.8474,0.4715,0.028362,3.1611,2.5162,2.0037,0.019636,4.4352,4.2676,-0.1524,1.0,-0.40,-0.560,-0.440,-0.6280,-3.14,5.0,2.14,-1.54,1.18,0.1833,0.7873,1.0,0.0,5.0,0.0
1,2,121,10,0.782776,1100,3,84645,240.0,1625.0,123.52,121.35,7,0.6555,0.6555,245815,0.6341,0.6341,0.3909,0.6667,0.6903,0.6903,8.449459e+08,78,50,754416.0,78.0,78.0,78.00,78.00,78.0,0.8478,0,0,0,6,0,0,...,-72.44,798.74,2.7180,-0.8294,1.0740,2.9194,2.1180,1.5666,0.120442,1.1963,1.0322,0.4843,0.2389,0.130160,2.7659,1.9523,1.4059,0.115277,3.2763,2.7962,-0.3097,1.0,-0.17,-0.275,-0.203,-0.2300,-1.38,6.0,0.54,-0.24,0.13,0.1926,-0.6787,1.0,0.0,5.0,0.0
2,3,126,10,0.500080,1100,3,83607,1800.0,1527.0,127.76,126.49,7,0.7542,0.7542,1385872,0.7542,0.7542,0.5508,0.7542,0.8091,0.7807,1.308478e+09,89,54,1037651.0,89.0,89.0,100.43,94.37,89.0,0.9175,0,0,0,13,0,0,...,-79.48,621.97,1.9592,-0.3632,3.2969,7.2072,5.7062,4.5627,0.226336,3.3277,3.4166,1.8321,0.9979,0.103307,6.8623,5.2963,4.1282,0.219729,8.1381,7.3269,-0.1909,1.0,-0.58,-0.540,-0.572,-0.3985,-5.18,13.0,2.89,-1.73,1.04,0.2521,0.7258,1.0,0.0,5.0,0.0
3,4,134,10,0.439874,1100,3,82642,7542.0,1730.0,132.94,133.58,7,0.8017,0.7881,704687,0.7881,0.7881,0.5923,0.7881,0.8230,0.8158,1.472752e+09,93,55,1115721.0,93.0,93.0,114.63,102.92,93.0,0.9688,0,0,0,4,0,0,...,18.15,429.81,2.5883,-0.8812,1.2950,2.5777,2.0830,1.6899,0.054630,1.3748,1.3421,0.7982,0.4810,0.081205,2.5571,2.0593,1.6653,0.056470,3.2516,3.0631,-0.1770,1.0,-0.75,-0.635,-0.745,-0.5100,-2.04,4.0,1.29,-0.89,0.66,0.2498,0.7119,1.0,0.0,5.0,0.0
4,5,109,9,0.502749,2900,4,79124,89.0,491.0,122.72,112.77,6,0.5263,0.5263,51985,0.5263,0.5263,0.3044,0.5405,0.5556,0.5455,1.442916e+09,60,21,536400.0,60.0,60.0,60.00,60.00,60.0,0.8451,0,0,0,26,0,0,...,-10559.05,708436.49,9.0293,-0.8760,6.3852,17.2599,14.2795,11.9179,0.085330,7.2175,6.2262,3.1446,1.6149,0.074286,15.9080,12.5688,9.9844,0.067540,17.5561,15.6079,-0.4444,1.0,-0.18,-0.280,-0.182,-0.4277,-11.12,26.0,6.11,-3.82,2.51,0.2282,-0.5399,0.0,0.0,5.0,0.0

In [39]:
print(data_train.shape)
print(data_train.info())

(29219, 771)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29219 entries, 0 to 29218
Columns: 771 entries, id to loss
dtypes: float64(731), int64(22), object(18)
memory usage: 171.9+ MB
None

In [40]:
data_cat = data_train.select_dtypes(include=['object']).copy()
data_cat.head()

,f137,f138,f206,f207,f276,f277,f338,f390,f391,f420,f469,f472,f534,f537,f626,f627,f695,f698
0,8090000000000000,754485076006959972352,3200000000000,38600000000000000,7900000000000000,683091368180479950848,7610000000000,10370164393071999997033054208,13621142007705000132589703585884798976,511000000000000,569877634360569973702656,3427303293502300223465356001280,240811094251680005357568,1185103615651699994464937312256,11724173453590999285553430528,16027029142402000396838501389877379072,8700000000000000000,8010000000000000000
1,2250000000000,15300000000000000,392000000000,1690000000000000,92300000000000,2140000000000000000,796594176,5098137566366599989877014528,5366154527659000357778647583412977664,1593188352,107000000000000000,9894337169928600158208,251470350285930004480,161196782629860003268263936,6391495663130699779035627520,7158933769610900052770065343332745216,5890000000000000000,5030000000000000000
2,186000000000000,6910365323840000000,23700000000000,389000000000000000,10300000000000,69200000000000000,461000000000,26400269714792999161039945728,36117033568522998807722429270944907264,63500000000000,313319151143610023936,222812827058929985669562368,116067852739909992448,61668865475731997253959680,36420952401170000260810932224,56027915541865997900093655676589441024,24512111987574001664,19855991371293999104
3,44500000000000000,11225194901267999096832,16098514954,35000000000000,22200000000000,295000000000000000,1330000000000,9333818143939599917454983168,12638526060843999893906772076814925824,9380000000000,2641626213765599994052608,24452856014536001129152839155712,202899352692079984640,126293716597939998795235328,15267506423634001098621059072,24362045267421999852972382580757233664,9660000000000000000,6960000000000000000
4,52152926246,108000000000000,442000000000,1870000000000000,3630000000000,23100000000000000,2240000000000,196004669899870011305513451520,428213273484070002013091334592080642048,659000000000000,68300000000000,922000000000000000,654000000000000000,89341826582645997305856,238204359524660008028924280832,550170020491249969340152709153269219328,108505460071560003584,94766610066210996224

In [41]:
print(data_cat.columns)
print(data_cat['f137'].value_counts())

Index(['f137', 'f138', 'f206', 'f207', 'f276', 'f277', 'f338', 'f390', 'f391',
       'f420', 'f469', 'f472', 'f534', 'f537', 'f626', 'f627', 'f695', 'f698'],
      dtype='object')
922000000000000000      228
3870000000000000        218
5770000000000000000     215
10500000000000000       208
1030000000000000        201
                       ...
230000000000.0            1
88900000000000            1
263000000000.0            1
42986223858734997504      1
697000000000.0            1
Name: f137, Length: 2398, dtype: int64

In [42]:
data_num = data_train.select_dtypes(include=['float64', 'int64']).copy()
data_num.head()

,id,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,f38,...,f743,f744,f745,f746,f747,f748,f749,f750,f751,f752,f753,f754,f755,f756,f757,f758,f759,f760,f761,f762,f763,f764,f765,f766,f767,f768,f769,f770,f771,f772,f773,f774,f775,f776,f777,f778,loss
0,1,126,10,0.686842,1100,3,13699,7201.0,4949.0,126.75,126.03,7,0.7607,0.7542,612922,0.7236,0.7236,0.5171,0.7236,0.8476,0.7876,1.097851e+09,89,66,998046.0,89.0,89.0,89.00,89.00,89.0,0.9271,0,0,0,5,0,0,...,-21.82,49.18,1.0435,-0.9066,1.5883,3.4154,2.8283,2.3451,0.030594,1.7418,1.5271,0.8474,0.4715,0.028362,3.1611,2.5162,2.0037,0.019636,4.4352,4.2676,-0.1524,1.0,-0.40,-0.560,-0.440,-0.6280,-3.14,5.0,2.14,-1.54,1.18,0.1833,0.7873,1.0,0.0,5.0,0.0
1,2,121,10,0.782776,1100,3,84645,240.0,1625.0,123.52,121.35,7,0.6555,0.6555,245815,0.6341,0.6341,0.3909,0.6667,0.6903,0.6903,8.449459e+08,78,50,754416.0,78.0,78.0,78.00,78.00,78.0,0.8478,0,0,0,6,0,0,...,-72.44,798.74,2.7180,-0.8294,1.0740,2.9194,2.1180,1.5666,0.120442,1.1963,1.0322,0.4843,0.2389,0.130160,2.7659,1.9523,1.4059,0.115277,3.2763,2.7962,-0.3097,1.0,-0.17,-0.275,-0.203,-0.2300,-1.38,6.0,0.54,-0.24,0.13,0.1926,-0.6787,1.0,0.0,5.0,0.0
2,3,126,10,0.500080,1100,3,83607,1800.0,1527.0,127.76,126.49,7,0.7542,0.7542,1385872,0.7542,0.7542,0.5508,0.7542,0.8091,0.7807,1.308478e+09,89,54,1037651.0,89.0,89.0,100.43,94.37,89.0,0.9175,0,0,0,13,0,0,...,-79.48,621.97,1.9592,-0.3632,3.2969,7.2072,5.7062,4.5627,0.226336,3.3277,3.4166,1.8321,0.9979,0.103307,6.8623,5.2963,4.1282,0.219729,8.1381,7.3269,-0.1909,1.0,-0.58,-0.540,-0.572,-0.3985,-5.18,13.0,2.89,-1.73,1.04,0.2521,0.7258,1.0,0.0,5.0,0.0
3,4,134,10,0.439874,1100,3,82642,7542.0,1730.0,132.94,133.58,7,0.8017,0.7881,704687,0.7881,0.7881,0.5923,0.7881,0.8230,0.8158,1.472752e+09,93,55,1115721.0,93.0,93.0,114.63,102.92,93.0,0.9688,0,0,0,4,0,0,...,18.15,429.81,2.5883,-0.8812,1.2950,2.5777,2.0830,1.6899,0.054630,1.3748,1.3421,0.7982,0.4810,0.081205,2.5571,2.0593,1.6653,0.056470,3.2516,3.0631,-0.1770,1.0,-0.75,-0.635,-0.745,-0.5100,-2.04,4.0,1.29,-0.89,0.66,0.2498,0.7119,1.0,0.0,5.0,0.0
4,5,109,9,0.502749,2900,4,79124,89.0,491.0,122.72,112.77,6,0.5263,0.5263,51985,0.5263,0.5263,0.3044,0.5405,0.5556,0.5455,1.442916e+09,60,21,536400.0,60.0,60.0,60.00,60.00,60.0,0.8451,0,0,0,26,0,0,...,-10559.05,708436.49,9.0293,-0.8760,6.3852,17.2599,14.2795,11.9179,0.085330,7.2175,6.2262,3.1446,1.6149,0.074286,15.9080,12.5688,9.9844,0.067540,17.5561,15.6079,-0.4444,1.0,-0.18,-0.280,-0.182,-0.4277,-11.12,26.0,6.11,-3.82,2.51,0.2282,-0.5399,0.0,0.0,5.0,0.0

In [43]:
data_num.columns

Index(['id', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9',
       ...
       'f770', 'f771', 'f772', 'f773', 'f774', 'f775', 'f776', 'f777', 'f778',
       'loss'],
      dtype='object', length=753)

In [44]:
data_num.isnull().sum()

id        0
f1        0
f2        0
f3        0
f4        0
       ...
f775    419
f776      1
f777      1
f778      1
loss      1
Length: 753, dtype: int64

In [45]:
data_num_imputed = data_num.fillna(data_num.mean(), inplace=False)
data_num_imputed.isnull().sum()

id      0
f1      0
f2      0
f3      0
f4      0
       ..
f775    0
f776    0
f777    0
f778    0
loss    0
Length: 753, dtype: int64

In [46]:
data_num_imputed.drop(columns='id', inplace=True)

In [47]:
data_num_imputed.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,f38,f39,...,f743,f744,f745,f746,f747,f748,f749,f750,f751,f752,f753,f754,f755,f756,f757,f758,f759,f760,f761,f762,f763,f764,f765,f766,f767,f768,f769,f770,f771,f772,f773,f774,f775,f776,f777,f778,loss
0,126,10,0.686842,1100,3,13699,7201.0,4949.0,126.75,126.03,7,0.7607,0.7542,612922,0.7236,0.7236,0.5171,0.7236,0.8476,0.7876,1.097851e+09,89,66,998046.0,89.0,89.0,89.00,89.00,89.0,0.9271,0,0,0,5,0,0,0.73180,...,-21.82,49.18,1.0435,-0.9066,1.5883,3.4154,2.8283,2.3451,0.030594,1.7418,1.5271,0.8474,0.4715,0.028362,3.1611,2.5162,2.0037,0.019636,4.4352,4.2676,-0.1524,1.0,-0.40,-0.560,-0.440,-0.6280,-3.14,5.0,2.14,-1.54,1.18,0.1833,0.7873,1.0,0.0,5.0,0.0
1,121,10,0.782776,1100,3,84645,240.0,1625.0,123.52,121.35,7,0.6555,0.6555,245815,0.6341,0.6341,0.3909,0.6667,0.6903,0.6903,8.449459e+08,78,50,754416.0,78.0,78.0,78.00,78.00,78.0,0.8478,0,0,0,6,0,0,0.65705,...,-72.44,798.74,2.7180,-0.8294,1.0740,2.9194,2.1180,1.5666,0.120442,1.1963,1.0322,0.4843,0.2389,0.130160,2.7659,1.9523,1.4059,0.115277,3.2763,2.7962,-0.3097,1.0,-0.17,-0.275,-0.203,-0.2300,-1.38,6.0,0.54,-0.24,0.13,0.1926,-0.6787,1.0,0.0,5.0,0.0
2,126,10,0.500080,1100,3,83607,1800.0,1527.0,127.76,126.49,7,0.7542,0.7542,1385872,0.7542,0.7542,0.5508,0.7542,0.8091,0.7807,1.308478e+09,89,54,1037651.0,89.0,89.0,100.43,94.37,89.0,0.9175,0,0,0,13,0,0,0.74710,...,-79.48,621.97,1.9592,-0.3632,3.2969,7.2072,5.7062,4.5627,0.226336,3.3277,3.4166,1.8321,0.9979,0.103307,6.8623,5.2963,4.1282,0.219729,8.1381,7.3269,-0.1909,1.0,-0.58,-0.540,-0.572,-0.3985,-5.18,13.0,2.89,-1.73,1.04,0.2521,0.7258,1.0,0.0,5.0,0.0
3,134,10,0.439874,1100,3,82642,7542.0,1730.0,132.94,133.58,7,0.8017,0.7881,704687,0.7881,0.7881,0.5923,0.7881,0.8230,0.8158,1.472752e+09,93,55,1115721.0,93.0,93.0,114.63,102.92,93.0,0.9688,0,0,0,4,0,0,0.77405,...,18.15,429.81,2.5883,-0.8812,1.2950,2.5777,2.0830,1.6899,0.054630,1.3748,1.3421,0.7982,0.4810,0.081205,2.5571,2.0593,1.6653,0.056470,3.2516,3.0631,-0.1770,1.0,-0.75,-0.635,-0.745,-0.5100,-2.04,4.0,1.29,-0.89,0.66,0.2498,0.7119,1.0,0.0,5.0,0.0
4,109,9,0.502749,2900,4,79124,89.0,491.0,122.72,112.77,6,0.5263,0.5263,51985,0.5263,0.5263,0.3044,0.5405,0.5556,0.5455,1.442916e+09,60,21,536400.0,60.0,60.0,60.00,60.00,60.0,0.8451,0,0,0,26,0,0,0.60315,...,-10559.05,708436.49,9.0293,-0.8760,6.3852,17.2599,14.2795,11.9179,0.085330,7.2175,6.2262,3.1446,1.6149,0.074286,15.9080,12.5688,9.9844,0.067540,17.5561,15.6079,-0.4444,1.0,-0.18,-0.280,-0.182,-0.4277,-11.12,26.0,6.11,-3.82,2.51,0.2282,-0.5399,0.0,0.0,5.0,0.0

In [48]:
data_num_shuffled = data_num_imputed.sample(frac=1, random_state=2)
data_num_shuffled.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,f38,f39,...,f743,f744,f745,f746,f747,f748,f749,f750,f751,f752,f753,f754,f755,f756,f757,f758,f759,f760,f761,f762,f763,f764,f765,f766,f767,f768,f769,f770,f771,f772,f773,f774,f775,f776,f777,f778,loss
20663,130,10,0.478819,1300,4,14694,1009.0,1691.0,129.54,129.61,11,0.7203,0.7203,236581,0.7203,0.7203,0.4794,0.7265,0.7589,0.7456,1.192125e+09,85,42,903125.0,85.00,85.00,104.77,94.07,85.0,0.8500,0,0,0,77,0,0,0.76015,...,32489.30,698940.25,5.8658,0.968200,29.3895,55.0445,46.8476,40.0383,0.056631,30.4776,25.7923,15.3338,9.2641,0.079191,52.6546,43.8197,36.6125,0.054356,62.5004,58.6241,-0.2411,1.0,-0.62,-0.660,-0.638,-0.4661,-35.89,77.0,22.59,-16.08,12.14,0.2759,-0.3767,1.0,0.0,7.0,0.0
11667,146,7,0.160590,3600,2,8423,436.0,196.0,149.28,146.14,14,0.7982,0.7778,241658,0.6741,0.6741,0.4639,0.6741,0.7778,0.7165,5.452707e+09,91,83,1209026.0,131.73,108.88,158.98,119.27,91.0,0.8505,0,0,0,37,0,0,0.70705,...,-1548.41,221013.20,6.5942,-1.007200,7.1543,19.3301,15.8819,13.2150,0.325698,9.3544,8.8325,5.2641,3.2830,0.227453,18.1058,14.4423,11.6875,0.316559,22.6757,20.8725,-0.2222,1.0,-0.45,-0.515,-0.485,-0.4238,-15.68,37.0,9.95,-7.22,5.62,0.2989,-0.5893,0.0,1.0,41.0,0.0
16542,130,10,0.436668,2600,4,7458,8018.0,2113.0,128.72,129.85,13,0.6692,0.6692,0,0.7131,0.6692,0.4697,0.7436,0.8131,0.7565,2.582581e+09,87,63,976401.0,87.00,87.00,107.24,96.28,87.0,0.9457,0,0,0,25,0,0,0.74460,...,2573.41,60310.02,5.0802,0.529800,8.7067,17.8767,15.3092,13.2057,0.080548,9.2700,8.0748,4.7449,2.8398,0.088999,16.8895,14.0498,11.7728,0.075303,20.0689,18.7980,-0.1869,1.0,-0.46,-0.370,-0.424,-0.3996,-9.99,25.0,5.27,-3.27,2.27,0.2261,-0.7905,0.0,0.0,52.0,33.0
19512,126,7,0.175131,1800,4,81452,958.0,269.0,125.84,126.26,11,0.7731,0.7419,133189,0.7480,0.7419,0.5340,0.7419,0.8070,0.8000,1.942065e+09,92,66,1100320.0,92.00,92.00,113.40,101.82,92.0,0.9020,0,0,0,41,0,0,0.79095,...,-1019.36,79577.99,5.1326,-0.783700,16.3527,30.4506,26.7533,23.7014,0.108598,18.1590,15.4541,10.0615,6.7012,0.140777,29.3662,25.3451,22.0632,0.107185,33.9862,32.4585,-0.1930,1.0,-0.37,-0.475,-0.373,-0.5771,-23.66,41.0,16.70,-12.64,9.94,0.2726,0.8513,0.0,0.0,80.0,0.0
19562,129,8,0.625807,1500,4,78328,5738.0,3694.0,129.00,129.00,10,0.7009,0.6613,1195601,0.6613,0.6613,0.4741,0.6949,0.7257,0.7193,1.349668e+09,82,68,867396.0,82.00,82.00,101.07,90.75,82.0,0.8632,0,0,0,2,0,0,0.71065,...,0.00,0.00,0.0000,-0.014042,0.5296,1.1286,0.8493,0.6398,0.024495,0.5296,0.5325,0.2773,0.1452,0.040530,1.1194,0.8393,0.6301,0.028195,1.4178,1.2666,-0.2743,1.0,-0.60,-0.530,-0.590,-0.5250,-1.05,2.0,0.56,-0.31,0.17,0.0661,-2.2763,1.0,0.0,13.0,0.0

In [49]:
loss = data_num_shuffled['loss'].copy()
data_num_shuffled.drop(columns='loss', inplace=True)
corr_matrix = data_num_shuffled.corr().abs()
corr_matrix.head()
corr_matrix.shape

(751, 751)

In [50]:
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
upper.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,f38,f39,...,f742,f743,f744,f745,f746,f747,f748,f749,f750,f751,f752,f753,f754,f755,f756,f757,f758,f759,f760,f761,f762,f763,f764,f765,f766,f767,f768,f769,f770,f771,f772,f773,f774,f775,f776,f777,f778
f1,NaN,0.076456,0.006456,0.695224,0.221588,0.080285,0.085211,0.169787,0.960977,0.998164,0.018564,0.195463,0.213286,0.042268,0.259655,0.324059,0.134079,0.247906,0.210085,0.226945,0.671963,0.224570,0.258159,0.274344,0.189480,0.023138,0.117149,0.052368,0.003818,0.183454,NaN,NaN,NaN,0.000331,NaN,NaN,0.433624,...,0.036607,0.010770,0.010457,0.157238,0.057878,0.093571,0.055774,0.054084,0.052029,0.547020,0.063529,0.051181,0.045561,0.038975,0.594834,0.061867,0.062440,0.062455,0.538995,0.049449,0.048589,0.210078,NaN,0.060773,0.079958,0.064677,0.102061,0.014234,0.000346,0.020667,0.023896,0.025584,0.069924,0.073416,0.024992,0.814013,0.115028
f2,NaN,NaN,0.007255,0.074071,0.143627,0.116928,0.192628,0.164915,0.114123,0.084643,0.016658,0.119522,0.121399,0.312322,0.126614,0.108415,0.294514,0.111600,0.075977,0.078660,0.190690,0.126513,0.515192,0.377466,0.147386,0.142552,0.106951,0.120733,0.314776,0.091699,NaN,NaN,NaN,0.052407,NaN,NaN,0.117830,...,0.096984,0.090496,0.100767,0.105699,0.042066,0.011261,0.038733,0.027426,0.017182,0.082146,0.009543,0.024794,0.058516,0.088580,0.080003,0.040197,0.028820,0.018470,0.097901,0.032299,0.024768,0.075972,NaN,0.135616,0.238360,0.150929,0.424681,0.004997,0.052417,0.036155,0.057044,0.073047,0.043001,0.176699,0.125312,0.071984,0.113225
f3,NaN,NaN,NaN,0.003335,0.003587,0.000369,0.004444,0.007993,0.007697,0.006739,0.005726,0.001421,0.001726,0.004082,0.000428,0.001511,0.003789,0.001514,0.004288,0.004250,0.002948,0.002310,0.006378,0.001819,0.006997,0.004797,0.004050,0.003285,0.001196,0.003427,NaN,NaN,NaN,0.000380,NaN,NaN,0.001536,...,0.001400,0.002055,0.004717,0.004527,0.004823,0.002660,0.002099,0.002462,0.002812,0.002100,0.002505,0.002435,0.002892,0.003263,0.001163,0.001903,0.002270,0.002621,0.002515,0.000937,0.001015,0.004311,NaN,0.002028,0.000354,0.001974,0.001233,0.001356,0.000340,0.002429,0.003148,0.003607,0.005355,0.001438,0.008537,0.006504,0.003668
f4,NaN,NaN,NaN,NaN,0.216823,0.101115,0.170705,0.221848,0.762757,0.710378,0.032159,0.242393,0.265200,0.076016,0.310314,0.364036,0.172493,0.299798,0.248708,0.272919,0.829618,0.288071,0.133091,0.190710,0.149659,0.077934,0.176466,0.050324,0.061135,0.227623,NaN,NaN,NaN,0.068062,NaN,NaN,0.485239,...,0.013137,0.072036,0.003504,0.179495,0.056637,0.190672,0.135960,0.134115,0.131328,0.616282,0.154955,0.137153,0.135616,0.129994,0.590981,0.143853,0.145195,0.145377,0.605275,0.132400,0.132738,0.248688,NaN,0.018419,0.008377,0.018045,0.032502,0.069885,0.068024,0.072306,0.074803,0.077302,0.002503,0.024191,0.011067,0.835254,0.112837
f5,NaN,NaN,NaN,NaN,NaN,0.067885,0.086038,0.004624,0.240322,0.225787,0.031400,0.076696,0.080554,0.010987,0.095151,0.116909,0.057048,0.097141,0.079590,0.087924,0.205146,0.083633,0.095374,0.074779,0.055713,0.016231,0.009271,0.038883,0.003833,0.065642,NaN,NaN,NaN,0.017696,NaN,NaN,0.159926,...,0.008143,0.026316,0.006102,0.041035,0.009840,0.047228,0.038652,0.038772,0.038613,0.187529,0.041113,0.036644,0.034125,0.030647,0.182155,0.041615,0.042854,0.043728,0.184137,0.038756,0.039483,0.079572,NaN,0.039978,0.041026,0.041257,0.034845,0.014746,0.017664,0.013900,0.013589,0.013480,0.022250,0.007775,0.035887,0.274808,0.794860

In [51]:
threshold = 0.8
col_to_drop = [column for column in upper.columns if any(upper[column]>threshold)]
len(col_to_drop)

547

In [52]:
data_num_shuffled.drop(columns=col_to_drop, inplace=True)
data_num_shuffled.columns

Index(['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f13', 'f14',
       ...
       'f736', 'f739', 'f740', 'f743', 'f746', 'f756', 'f764', 'f775', 'f776',
       'f778'],
      dtype='object', length=204)

In [53]:
corr_tar = data_num_shuffled.corrwith(loss).sort_values()
print(corr_tar.head(30))
print(corr_tar.tail(30))
corr_tar_df = corr_tar.to_frame().transpose()
corr_tar_df.isna()

f69    -0.015484
f286   -0.013477
f672   -0.013271
f1     -0.012342
f36    -0.012086
f66    -0.012022
f775   -0.011920
f393   -0.011850
f288   -0.011577
f84    -0.011017
f429   -0.010801
f43    -0.010797
f756   -0.010491
f314   -0.010409
f433   -0.009672
f657   -0.009577
f631   -0.009571
f82    -0.009555
f776   -0.009312
f290   -0.008914
f54    -0.008777
f191   -0.008755
f112   -0.008217
f135   -0.008207
f418   -0.008197
f660   -0.008150
f588   -0.008086
f669   -0.007918
f72    -0.007793
f335   -0.007432
dtype: float64
f479    0.007721
f142    0.007796
f514    0.007877
f648    0.007962
f646    0.008085
f778    0.008124
f344    0.008277
f201    0.008473
f47     0.009942
f5      0.010245
f221    0.010333
f620    0.010397
f615    0.011412
f509    0.013164
f218    0.013416
f13     0.013956
f556    0.020790
f471    0.034109
f536    0.055200
f33          NaN
f34          NaN
f35          NaN
f37          NaN
f38          NaN
f678         NaN
f700         NaN
f701         NaN
f702         NaN
f736         NaN
f764         NaN
dtype: float64

,f69,f286,f672,f1,f36,f66,f775,f393,f288,f84,f429,f43,f756,f314,f433,f657,f631,f82,f776,f290,f54,f191,f112,f135,f418,f660,f588,f669,f72,f335,f8,f526,f150,f637,f647,f634,f140,...,f746,f743,f81,f3,f213,f251,f451,f479,f142,f514,f648,f646,f778,f344,f201,f47,f5,f221,f620,f615,f509,f218,f13,f556,f471,f536,f33,f34,f35,f37,f38,f678,f700,f701,f702,f736,f764
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True

In [54]:
col_to_drop_1 = corr_tar_df.columns[corr_tar_df.isna().any()]
print(len(col_to_drop_1))
print(col_to_drop_1)

11
Index(['f33', 'f34', 'f35', 'f37', 'f38', 'f678', 'f700', 'f701', 'f702',
       'f736', 'f764'],
      dtype='object')

In [55]:
data_num_shuffled.drop(columns=col_to_drop_1, inplace=True)

In [56]:
data_num_shuffled.columns

Index(['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f13', 'f14',
       ...
       'f725', 'f733', 'f739', 'f740', 'f743', 'f746', 'f756', 'f775', 'f776',
       'f778'],
      dtype='object', length=193)

In [57]:
X_feat = data_num_shuffled.copy()

In [58]:
Y_tar = loss.copy()

In [59]:
Y_tar[Y_tar>0] = 1
Y_tar.value_counts()

0.0    26598
1.0     2621
Name: loss, dtype: int64

In [60]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_feat, Y_tar, test_size=0.2, random_state=42)
ss = StandardScaler()
X_train = ss.fit_transform(x_train)
X_test = ss.transform(x_test)

In [61]:
y_train = np.array(y_train).reshape((-1, ))
y_test = np.array(y_test).reshape((-1, ))

In [62]:
# function for calculating cross validation scores for evaluating model performance on train data and test data
def scores(X_train, y_train, X_test, y_test, model):
    from sklearn.model_selection import cross_val_score, ShuffleSplit
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=42) # shufflesplit is a cross validation strategy that is best used when n_features < n_samples
    train_scores = cross_val_score(estimator = model, X = X_train, y = y_train, cv = cv)
    test_scores = cross_val_score(estimator = model, X = X_test, y = y_test, cv = cv)
    return [round(train_scores.mean(), 4), round(test_scores.mean(),4)]

In [63]:
# function to fit and evaluate model performance
def fit_and_evaluate(model):
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions and evalute
    y_pred = model.predict(X_test)
    cross_val_scores = scores(X_train, y_train, X_test, y_test, model)
    
    # calculate accuracy and f_score for model performance
    from sklearn.metrics import accuracy_score, f1_score
    accuracy = accuracy_score(y_test, y_pred, normalize=True)
    f_score = f1_score(y_test, y_pred, average='macro')
    
    # dictionary for storing all the above values
    metric = dict()
    metric['cv_scores'] = cross_val_scores
    metric['accuracy'] = round(accuracy,4)
    metric['f_score'] = round(f_score,4)
    
    # Return the performance metric 
    return metric

In [64]:
import warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [65]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
#from xgboost import XGBClassifier

# logistic regression 
logistic = LogisticRegression(max_iter = 50, random_state=42)
log_c = fit_and_evaluate(logistic)
print('performance of logistic regression on train and test data:', log_c['cv_scores'])
log_c.pop('cv_scores')
print(log_c)
df_log = pd.DataFrame(log_c, index=[0])
print(df_log)

# Random forest classification
RFC = RandomForestClassifier(n_estimators = 15, random_state=42)
random = fit_and_evaluate(RFC)
print('performance of Random Forest Classifier on train and test data:', random['cv_scores'])
random.pop('cv_scores')
print(random)
df_rand = pd.DataFrame(random, index=[1])
print(df_rand)

# Xgboost classification
#conda install -c anaconda py-xgboost

'''gb = XGBClassifier()
gb_c = fit_and_evaluate(gb)
print('performance of XGB Classifier on train and test data:', gb_c['cv_scores'])
gb_c.pop('cv_scores')
print(gb_c)
df_gb = pd.DataFrame(gb_c, index=[2])
print(df_gb)

frames = [df_log, df_rand, df_gb]
model_compare_df = pd.concat(frames)

'''
from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive_cross = fit_and_evaluate(naive)
print('performance of nave on train and test data:', naive_cross['cv_scores'])
naive_cross.pop('cv_scores')
#print(model_compare_df)

performance of logistic regression on train and test data: [0.9114, 0.9163]
{'accuracy': 0.9163, 'f_score': 0.4822}
   accuracy  f_score
0    0.9163   0.4822
performance of Random Forest Classifier on train and test data: [0.9102, 0.9194]
{'accuracy': 0.9153, 'f_score': 0.4897}
   accuracy  f_score
1    0.9153   0.4897
performance of nave on train and test data: [0.5322, 0.3695]

[0.5322, 0.3695]

In [66]:
# finding least important features from random forest classification so as to see if we can improve our model performance or we can get same performance with less features
feature_importances = RFC.feature_importances_
feature_importances = pd.DataFrame({'feature': list(X_feat.columns), 'importance': feature_importances}).sort_values('importance', ascending = True)
print(feature_importances['importance'].mean()/2) # threshold for filtering least important features
least_important_feat = list(feature_importances[feature_importances['importance'] < 0.0025]['feature'])
len(least_important_feat)

0.0025906735751295333

11

In [67]:
# creating dataframe with important features
X_feat_imp = X_feat.drop(columns=least_important_feat, inplace=False)
len(X_feat_imp.columns)

182

In [68]:
x_train_imp, x_test_imp, y_train, y_test = train_test_split(X_feat_imp, Y_tar, test_size=0.2, random_state=42)
ss = StandardScaler()
X_train_imp = ss.fit_transform(x_train_imp)
X_test_imp = ss.transform(x_test_imp)

In [69]:
# converting y to one-dimensional array
y_train = np.array(y_train).reshape((-1, ))
y_test = np.array(y_test).reshape((-1, ))

In [70]:
def fit_and_evaluate_imp(model):
    
    # Train the model
    model.fit(X_train_imp, y_train)
    
    # Make predictions and evalute
    y_pred = model.predict(X_test_imp)
    cross_val_scores = scores(X_train_imp, y_train, X_test_imp, y_test, model)
    
    # calculate accuracy and f_score for model performance
    from sklearn.metrics import accuracy_score, f1_score
    accuracy = accuracy_score(y_test, y_pred, normalize=True)
    f_score = f1_score(y_test, y_pred, average='macro')
    
    # dictionary for storing all the above values
    metric = dict()
    metric['cv_scores'] = cross_val_scores
    metric['accuracy'] = round(accuracy,4)
    metric['f_score'] = round(f_score,4)
    
    # Return the performance metric 
    return metric

In [71]:
# Random forest classification with important features
RFC_imp = RandomForestClassifier(n_estimators = 15, random_state=42)
random_imp = fit_and_evaluate_imp(RFC_imp)
print('performance of Random Forest Classifier on train and test data:', random_imp['cv_scores'])
random_imp.pop('cv_scores')
print(random_imp)
df_rand_imp = pd.DataFrame(random_imp, index=[0])
print(df_rand_imp)

performance of Random Forest Classifier on train and test data: [0.9107, 0.9192]
{'accuracy': 0.9139, 'f_score': 0.4775}
   accuracy  f_score
0    0.9139   0.4775

In [72]:
data_test = pd.read_csv('test_v2.csv')

In [73]:
data_test.shape

(215, 770)

In [74]:
data_test.columns

Index(['id', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9',
       ...
       'f769', 'f770', 'f771', 'f772', 'f773', 'f774', 'f775', 'f776', 'f777',
       'f778'],
      dtype='object', length=770)

In [75]:
print(X_feat.columns)
print(X_feat_imp.columns)

Index(['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f13', 'f14',
       ...
       'f725', 'f733', 'f739', 'f740', 'f743', 'f746', 'f756', 'f775', 'f776',
       'f778'],
      dtype='object', length=193)
Index(['f1', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f13', 'f14', 'f16',
       ...
       'f696', 'f715', 'f733', 'f739', 'f740', 'f743', 'f746', 'f756', 'f775',
       'f778'],
      dtype='object', length=182)

In [76]:
test_feat = data_test[X_feat.columns]
test_feat_imp = data_test[X_feat_imp.columns]
print(test_feat.columns)
print(test_feat_imp.columns)

Index(['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f13', 'f14',
       ...
       'f725', 'f733', 'f739', 'f740', 'f743', 'f746', 'f756', 'f775', 'f776',
       'f778'],
      dtype='object', length=193)
Index(['f1', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f13', 'f14', 'f16',
       ...
       'f696', 'f715', 'f733', 'f739', 'f740', 'f743', 'f746', 'f756', 'f775',
       'f778'],
      dtype='object', length=182)

In [77]:
print(test_feat.isnull().sum())
print(test_feat_imp.isnull().sum())

f1      0
f2      0
f3      0
f4      0
f5      0
       ..
f746    2
f756    1
f775    4
f776    1
f778    1
Length: 193, dtype: int64
f1      0
f3      0
f4      0
f5      0
f6      0
       ..
f743    1
f746    2
f756    1
f775    4
f778    1
Length: 182, dtype: int64

In [78]:
test_feat_imputed = test_feat.fillna(test_feat.mean(),inplace=False)
test_feat_imp_imputed = test_feat_imp.fillna(test_feat_imp.mean(),inplace=False)

In [79]:
print(test_feat_imputed.isnull().sum())
print(test_feat_imp_imputed.isnull().sum())

f1      0
f2      0
f3      0
f4      0
f5      0
       ..
f746    0
f756    0
f775    0
f776    0
f778    0
Length: 193, dtype: int64
f1      0
f3      0
f4      0
f5      0
f6      0
       ..
f743    0
f746    0
f756    0
f775    0
f778    0
Length: 182, dtype: int64

In [80]:
ss = StandardScaler()
test_feat_scaled = ss.fit_transform(test_feat_imputed)
test_feat_imp_scaled = ss.fit_transform(test_feat_imp_imputed)

In [81]:
predicted_val = RFC.predict(test_feat_scaled)
predicted_val_imp = RFC_imp.predict(test_feat_imp_scaled)
df_val = pd.DataFrame({'loss_as_binary':predicted_val})
df_val_imp = pd.DataFrame({'loss_as_binary':predicted_val_imp})
print(df_val)
print(df_val_imp)

     loss_as_binary
0               1.0
1               0.0
2               0.0
3               0.0
4               0.0
..              ...
210             1.0
211             1.0
212             1.0
213             1.0
214             0.0

[215 rows x 1 columns]
     loss_as_binary
0               0.0
1               0.0
2               0.0
3               0.0
4               0.0
..              ...
210             0.0
211             0.0
212             0.0
213             0.0
214             0.0

[215 rows x 1 columns]

In [82]:
predicted_prob = RFC.predict_proba(test_feat_scaled)
predicted_prob_imp = RFC_imp.predict_proba(test_feat_imp_scaled)
df_prob = pd.DataFrame({'no_default': predicted_prob[:, 0], 'default': predicted_prob[:, 1]})
df_prob_imp = pd.DataFrame({'no_default': predicted_prob_imp[:, 0], 'default': predicted_prob_imp[:, 1]})
print(df_prob)
print(df_prob_imp)

     no_default   default
0      0.466667  0.533333
1      0.600000  0.400000
2      0.866667  0.133333
3      0.733333  0.266667
4      0.533333  0.466667
..          ...       ...
210    0.466667  0.533333
211    0.466667  0.533333
212    0.466667  0.533333
213    0.466667  0.533333
214    0.866667  0.133333

[215 rows x 2 columns]
     no_default   default
0      0.733333  0.266667
1      0.800000  0.200000
2      0.533333  0.466667
3      0.533333  0.466667
4      0.733333  0.266667
..          ...       ...
210    0.600000  0.400000
211    0.800000  0.200000
212    0.733333  0.266667
213    0.600000  0.400000
214    0.866667  0.133333

[215 rows x 2 columns]

In [83]:
submission = pd.DataFrame()
submission['id'] = data_test.id
submission['loss_as_binary'] = df_val.loss_as_binary
submission['default_prob'] = round(df_prob.default,2)
print(submission)

         id  loss_as_binary  default_prob
0    105472             1.0          0.53
1    105473             0.0          0.40
2    105474             0.0          0.13
3    105475             0.0          0.27
4    105476             0.0          0.47
..      ...             ...           ...
210  105682             1.0          0.53
211  105683             1.0          0.53
212  105684             1.0          0.53
213  105685             1.0          0.53
214  105686             0.0          0.13

[215 rows x 3 columns]

In [84]:
submission.head()

       id  loss_as_binary  default_prob
0  105472             1.0          0.53
1  105473             0.0          0.40
2  105474             0.0          0.13
3  105475             0.0          0.27
4  105476             0.0          0.47

In [85]:
Submission = submission.to_csv(index=False)

In [86]:
submission_imp = pd.DataFrame()
submission_imp['id'] = data_test.id
submission_imp['loss_as_binary'] = df_val_imp.loss_as_binary
submission_imp['default_prob'] = round(df_prob_imp.default,2)
print(submission_imp)

         id  loss_as_binary  default_prob
0    105472             0.0          0.27
1    105473             0.0          0.20
2    105474             0.0          0.47
3    105475             0.0          0.47
4    105476             0.0          0.27
..      ...             ...           ...
210  105682             0.0          0.40
211  105683             0.0          0.20
212  105684             0.0          0.27
213  105685             0.0          0.40
214  105686             0.0          0.13

[215 rows x 3 columns]

In [87]:
submission_imp.head()

       id  loss_as_binary  default_prob
0  105472             0.0          0.27
1  105473             0.0          0.20
2  105474             0.0          0.47
3  105475             0.0          0.47
4  105476             0.0          0.27